services:
  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - devkube

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=redis-app,redis-datasource
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
      - tempo
      - redis
      - cratedb
    networks:
      - devkube

  tempo:
    image: grafana/tempo:2.3.0
    command: [ "-config.file=/etc/tempo/tempo.yaml" ]
    ports:
      - "3200:3200"   # tempo
      - "4317:4317"   # otlp grpc
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo/tempo.yaml
      - tempo_data:/tmp/tempo
    networks:
      - devkube

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    command: redis-server --requirepass "" --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - devkube

  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - devkube

  cratedb:
    image: crate
    platform: linux/arm64
    ports:
      - "4200:4200"   # HTTP
      - "5432:5432"   # PostgreSQL
    environment:
      - CRATE_HEAP_SIZE=2g
      - CRATE_JAVA_OPTS=-Xms2g -Xmx2g
      - CRATE_CLUSTER_NAME=devkube-cluster
    volumes:
      - cratedb_data:/data
    command: 
      - crate
      - -Cnode.name=cratedb-node
      - -Ccluster.name=devkube-cluster
      - -Cnetwork.host=0.0.0.0
      - -Cdiscovery.type=single-node
    networks:
      - devkube

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"    # AMQP protocol port
      - "15672:15672"  # Management UI port
      - "15692:15692"  # Prometheus metrics port
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_PLUGINS=rabbitmq_management rabbitmq_prometheus
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - devkube

networks:
  devkube:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
  tempo_data:
  redis_data:
  minio_data:
  cratedb_data:
  rabbitmq_data: