apiVersion: 1
datasources:
  - name: CrateDB
    type: postgres
    access: proxy
    url: cratedb:5432
    database: crate
    user: crate
    secureJsonData:
      password: ""
    jsonData:
      sslmode: 'disable'
      postgresVersion: 1400
      timescaledb: false
    isDefault: false
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis:6379
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
      tlsAuth: false
      tlsSkipVerify: true
      acl: false
      maxRetries: 3
      sentinelMode: false
      sentinelName: ""
      commandTimeout: 5
      poolMinSize: 1
      poolMaxConnLifetime: 0
      enableTLSAuth: false
    isDefault: false
    editable: true

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: Tempo
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      search:
        hide: false
      tracesToLogs:
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [{ key: 'service.name', value: 'service' }]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
    isDefault: false
    editable: true